[package]
name = "blogdown-dao"
version = "0.1.0"
edition = "2021"

[dependencies]
blogdown-model = { path = "../blogdown-model" }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio", "chrono"] }